### ISSUE TITLE
Feed-picker, search- and filter-button not reappearing

### ISSUE THREAD

**Issue by OIL1I** [astarub/campus_app#108]
When scrolling down until the feed-picker disappears, and than scrolling back up, bringing the feed entries back to their original position, the buttons stay hidden.

![Screenshot_20230627_140752](https://github.com/astarub/campus_app/assets/78214664/91ec6b64-e844-454c-a33d-2b763cd21232)

You have to scroll further down and than up again to make them reappear

**Comment by henry-herrmann** [comment]
Are you running the app in debug mode (built on your own machine)?

**Comment by OIL1I** [comment]
the problem occurs in emulation as well as on the released app from the playstore

**Comment by henry-herrmann** [comment]
I can't really reproduce the issue when scrolling down to the very bottom of the news feed but if you scroll down just a centimeter or two and then scroll back up, the buttons stay hidden. Do you mean that?

**Comment by henry-herrmann** [comment]
Now I see it. I'll look into it.
