### ISSUE TITLE
Application Data can be Backed up

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#122]
Currently the [android:allowBackup] flag is missing, it should be set to false. Currently anyone can backup the application data via adb meaning a user who has USB debugging enabled can have their data copied off of the device. Regarding the fact that there is a planned option for authentication/university login maybe even with stored credentials and the semester ticket this flag should be changed to address this issue.

**Comment by henry-herrmann** [comment]
You are right, if the user's Android version is lower than 12. If it's 12 or higher, D2D transfers cannot be disabled, see: https://developer.android.com/about/versions/12/behavior-changes-12#backup-restore.
I'll still set the allowBackup flag to false. 
Thanks for opening up the issue.

**Comment by MixColumns** [comment]
@henry-herrmann are you sure you set the flag? afak it is still not set. Maybe i am wrong though can you please recheck?

**Comment by henry-herrmann** [comment]
Yeah, it's updated in https://github.com/astarub/campus_app/blob/master/android/app/src/main/AndroidManifest.xml.
