### ISSUE TITLE
Cachable HTTPS responses from Endpoints

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#125]
Some endpoints like https://asta-bochum.de/wp-json/tribe/events/v1/events?per_page=1 have set the header Cache-Control: max-age=0 however this does not stop third party or for example a proxy to not cache the file. Cache-control: no-store / Pragma: no-cache should be used instead in my oppinion

**Comment by domai-tb** [comment]
This is irrelevant for the app.
