### ISSUE TITLE
Datenschutzerklärung, Impressum und API Website

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#126]
- Datenschutzerklärung und Impressum sollten nicht über den Browser geladen sondern nativ in der App hinterlegt sein, sodass diese auch ohne Internetzugang und ohne das Laden externer Seiten eingesehen werden können
- Der Link um Matamo für Ihren Browser zu deaktivieren fehlt/die Erklärung ist oudated
- In der Sektion Campus App sollte meiner Meinung nach explizit noch erwähnt werden dass die App Daten von der Asta Seite wie beispielsweise die Eventliste läd - dabei werden auch Daten übertragen

Es gibt auch noch einige generell Probleme mit der Seite, die die API bereitstellt, beispielsweise:
- anti-clickjacking X-Frame-Options header ist nicht gesetzt
- Strict-Transport-Security HTTP header ist nicht defined
- X-Content-Type-Options header ist nicht gesetzt
- XML-RPC ist noch aktiviert
- WordPress RSS Aggregator by Feedzy Plugin < 4.1.1 ist für Cross Site Scripting (XSS) anfällig und outdated
- wildcard Zertifikat in Nutzung: *.asta-bochum.de.

**Comment by henry-herrmann** [comment]
Headers were set, wildcard cert is removed and I'll address the points once I get to it. 
For the privacy policy, it is unnecessary to include AStA servers, as we're the service which would be redundant entry.
