### ISSUE TITLE
Dark Theme page swap sparkle effect

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#131]
Currently when using the dark theme when pressing buttons in the bottom nove white sparkles will appear and spread within the square of the UI element. Even though the transition is fast it looks a bit buggy and im not sure if the white sparkles are intentional or needed. It would probably be more performant to only use the dark and bright button color when an item gets selected

**Comment by domai-tb** [comment]
Can you please provide a screenshot or video from this? I'm not sure what effect you mean / could not replicate this behavior.

**Comment by MixColumns** [comment]
Turn the birghtness all the way up
enable dark theme
switch between the icons in the bottom nav and observe white pixel noise while the symbol is activated

sadly my phone has no native screen recording but if you let me know about an open source screen recorder app  i will gladly provide a video
