### ISSUE TITLE
Addition to the readme / wiki

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#154]
Currently it states:

"We work with feature branches, which means whenever you work on a feature or bug you do that on the explicit branch. If the feature is ready, we merge it with a pull-request into the main/master branch. In some cases, the app team can bypass that rule if deemed necessary."

There are a lot of stale branches and not very informative branch names. Could you please add a small specification which branches are used for which purposes? I think this would be useful in order to know where to commit to.

**Comment by domai-tb** [comment]
Yeah, our branching got a bit messy over time. We will address this in the next meetings. 

But if you want to contribute, just create a feature branch:

1. Fork of the repository
2. Create a new branch and name it brief and descriptive to the feature you want to implement
3. Implement your feature as you want and open a PR to `master`

The PR should explain all details on what you added and what you changed.
