### ISSUE TITLE
Semesterticket WiSe wird nicht automatisch nachgeladen, Login Daten werden nicht gespeichert.

### ISSUE THREAD

**Issue by Maximilian-tek** [astarub/campus_app#179]
Problemstellung:
App im normalen Gebrauch für Speiseplan, Ticket und Mensa-Guthaben also mehrfach die Woche geöffnet. Beim Nutzen der App im WiSe wurde noch das Ticket vom SoSe angezeigt, und musste nun manuell aktualisiert werden durch auch erneute Eingabe der Zugangsdaten. 

Erwartete Funktion:
Durch den Text, dass die Zugangsdaten gespeichert werden, wird vermutet, dass diese Aktualisierung jedes Semester automatisch geschieht.

System:
Fairphone 5 mit Custom Android ROM (e/OS) mit MicroG
Campus App by AStA via Aurora Store
Campus App hat die folgenden besonderen Berechtigungen: (Ausgestellt sind Notification, weitere wurden seitens der App nicht angefragt (yeah<3))
Apps die länger als 8 Wochen nicht genutzt werden werden automatisch die Berechtigungen entzogen ist für diese App ausgestellt.

**Comment by domai-tb** [comment]
Can confirm. I think it has something to do how [`ticketUsecases.getTicketDetails()`](https://github.com/astarub/campus_app/blob/b33887057c53a0a8a88350f7e9c2dbd32f412815/lib/pages/wallet/widgets/wallet.dart#L67C5-L67C89) is handled. As far as I could see, just [`ticketRepository.loadTicket()`](https://github.com/astarub/campus_app/blob/b33887057c53a0a8a88350f7e9c2dbd32f412815/lib/pages/wallet/ticket/ticket_repository.dart#L29) will delete the saved ticket. 

@henry-herrmann Do you have time to look into this problem?
