### ISSUE TITLE
🛰️ Version 1.1 Update

### ISSUE THREAD

**Issue by C4s4r** [astarub/campus_app#37]
<p align="center"><img src="https://user-images.githubusercontent.com/56138477/201695385-c84ffdab-2f11-445f-8d35-83b94fcf5587.png" width="450"></p>

This issue keeps track of all tasks that have to be done until version 1.1 of the Campus App can be published for production.

## General
- [ ] AStA news feed integration
- [x] Reposition the _Leitwarte_ emergency call
- [x] https://github.com/astarub/campus_app/pull/77
- [x] Add the _Tanzkreis_ on the more page

## User Interface
- [x] https://github.com/astarub/campus_app/pull/73
- [x] https://github.com/astarub/campus_app/pull/78
- [x] https://github.com/astarub/campus_app/pull/79

## Backend
- [x] https://github.com/astarub/campus_app/pull/46
- [x] Push-notifications from external source (https://github.com/astarub/campus_app/pull/46)
- [x] Switch to new Mensa database server

## General Issues
- [x] https://github.com/astarub/campus_app/issues/38
- [x] https://github.com/astarub/campus_app/issues/39
- [x] https://github.com/astarub/campus_app/issues/44
- [x] https://github.com/astarub/campus_app/issues/63
- [ ] https://github.com/astarub/campus_app/issues/5

**Comment by ThetaEdra** [comment]
Should also be added to https://github.com/astarub/campus_app/milestone/2 right?

**Comment by C4s4r** [comment]
Normally we only add single task issues or full feature pull requests to the milestone.
These version issues are a general overview and therefore open until everything is done.
