### ISSUE TITLE
BottomNavMenu animation delayed on first page switch

### ISSUE THREAD

**Issue by C4s4r** [astarub/campus_app#5]
When starting the app and switching to a different page by tapping on an item in the BottomNavMenu, the animation (that indicates that this item is the now active one) is delayed.

https://user-images.githubusercontent.com/56138477/186229386-cb01a9a6-9c3f-45c0-89f1-8f9ad9f3da4c.mp4

**Comment by MixColumns** [comment]
Anything new on this?

**Comment by henry-herrmann** [comment]
Nope, we have no idea about where this is coming from. 
Since it's probably caused by deep down Flutter mechanics and it doesn't really prevent the day-to-day user from using the app.
