### ISSUE TITLE
Feed snackbar blocks page navigation

### ISSUE THREAD

**Issue by ghost** [astarub/campus_app#64]
Wenn ich auf der ersten Page die Suche nutze bekomme ich die Meldung dass es noch nichts zu suchen gibt, ich kann jedoch erst zu einer anderen Seite wechseln wenn die Meldung wieder vollständig verschwunden ist. Die Seiten sollten vorher schon wechselbar sein, die Nachricht sollte wahlweise beim wechsel verschwinden oder nach einer gewissen Zeit verschwinden aber Navigation zu einer anderen Seite möglich sein.

**Comment by C4s4r** [comment]
Thanks for the feedback. I already noticed this behaviour when I first implemented the  Snackbar.
As of now, I haven't found an easy solution for this. Most people will only tap on this once and then won't do it ever again, until we announce that the search feature is added.

If you find a solution for this misbehaviour, feel free to open a pull request 😊
